version: '3.2'
services:
  api:
    image: marem/springpetclinic_api
    ports:
      - 9966:9966
    networks:
      - spring-petclinic
  front:
    image: marem/springpetclinic_front
    depends_on:
      - api
    ports:
      - 8081:8081
    networks:
      - spring-petclinic
networks:
    spring-petclinic:
